const cards = [
  {
    from: "Madrid",
    to: "Stockholm",
    type: "flight",
    number: "SK455",
    seat: "3A",
    gate: "45B",
    additional: "",
    latitude: 40.4165,
    longitude: -3.7026,
  },
  {
    from: "Apatity",
    to: "Oslo",
    type: "flight",
    number: "",
    seat: "",
    gate: "",
    additional: "",
    latitude: 67.5641,
    longitude: 33.4031,
  },
  {
    from: "Stockholm",
    to: "New York",
    type: "flight",
    number: "SK22",
    seat: "7B",
    gate: "22",
    additional: "",
    latitude: 59.3326,
    longitude: 18.0649,
  },
  {
    from: "Barcelona",
    to: "Madrid",
    type: "the airport bus",
    number: "",
    seat: "",
    gate: "",
    additional: "",
    latitude: 41.3888,
    longitude: 2.159,
  },
  {
    from: "London",
    to: "Dublin",
    type: "train",
    number: "677A",
    seat: "40",
    gate: "",
    additional: "",
    //from
    latitude: 51.51,
    longitude: -0.13,
    //to
    latitude_to: 53.344,
    longitude_to: -6.2672,
  },
  {
    from: "Oslo",
    to: "Berlin",
    type: "flight",
    number: "",
    seat: "15B",
    gate: "",
    additional: "",
    latitude: 59.9127,
    longitude: 10.7461,
  },
  {
    from: "New York",
    to: "Apatity",
    type: "flight",
    number: "",
    seat: "17D",
    gate: "",
    additional: "",
    latitude: 40.7143,
    longitude: -74.006,
  },
  {
    from: "Berlin",
    to: "London",
    type: "train",
    number: "78A",
    seat: "45B",
    gate: "",
    additional: "",
    //from
    latitude: 52.5244,
    longitude: 13.4105,
    //to
    latitude_to: 51.51,
    longitude_to: -0.13,
  },
];

export default cards;
